
language: node_js
node_js: stable
dist: trusty
sudo: required
addons:
  firefox: latest
  sauce_connect: true
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- npm install -g bower polylint web-component-tester
- bower install
script:
- polylint
- xvfb-run wct
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct -s 'default'; fi
env:
  global:
  - secure: MW01W14CHt59QzSjv0vxFHngNmiU4CneTSUfDrChVk+KKh1ukGKARtebVAt/yVqVShDjQ/XdnAdojgxfumvc//dLzSMMlUmSykwSM7tqPm+Ds/sytnmfPwGvCkBpxzYyntugg2HXRFJwH1usmkAwRApzhdvAQejRqpVAVSdU6H7bcy4iKVajeOSW3P8ZLLWk0H+UhFp2JJhub1+uILuhZIWGXpCO2V9ObqOCGzMiUseIQ7BYb5UOej3E5HVJ+crN1Clt2IEvwDyjeImhsD4LuaQqhUh9w7NvTGcvelUtyofULcu4+n9j9Ve6tP3VxPlFZCBoEtODoeJxh1sQNqLgCUlVsKaxMlAqdTfGdKl4gLo4mIBHWsZnbG0JE8Mj1a242PQM8YJrKVYXOsB4R900q0QgzmXH0IOvmsfC0gxWwNpUfF4OfCpez0DmYJP//2XNkEtfoJcutpuiVUhjs+R2p4j1nO4wys1Uh67hNKWrhmOU3qvSc4J5TjHDa/SxdDoXJ2fmbwi1Q52fDY9QJn+fvYlofSaQESKNviM7SOtmzvksh7pPdpjHuKH8Ayw1CvVBxxQbqqwLZjS8Dht7+uN5j/HpBQdAcvrYu73FODZfGZlbGhg8CkkrWgSXE9zOVSwFAdMi7p71Vx6p0AzEPv/LJtcnz+SI9r8brLkj3Var0WI=
  - secure: BGMaZdfeRfaZnmoGcTSdd38MF5EnLyMRtKx1fvGoG39O7dck9da+DrFsIlL3nqExnFyPvrXX57No8MDHKv3u5fgflJWgEBfGeNJlxj37mBY6MRFMdfjJt9TBxWTVdEfQrX5qzcJUGaKd/PiGWl+uF+4IaEjUP1GDHWdLKQHwbl22FGBIW5b5/vldyXab9+MXkpG1+dJ0pJSulTtVzTI6tA3ZKoIaDCj+VpOcpbAdBvOf1i45kEBWON27ZDNLws/HTwo8r514DpQuZy3xgdIJa8hIzlygGJs8tf+cpf72IvFDfMudnHdCcEFmIplQFRP6SYGLucH9hnCEBk2Rj+ifhLHHJ1rpLGlfJi3gCzg3fPl+TGgCwLuotGN1CPCFuoht8rZJRwHjDsGlcUuZe9B6Y77J7AZF39EsUpg4OvZ9l3bZj8e6TFnoJJ1RFUNUvMqS/7Vc9mrG+18C2m17f51sTqzEwr6LjWcyI3SVInfFkpTzJaPhJ3pE44K8SWNUdvd63J0bt62qEirMWzw7lHHuJZ5bdbrjLeDfVRdJEJccwDeMOmIY6oqcn6BdDc1CcPQvWUk9ZqCGXaBzDd5rgwzqXfYAqwrCRhFUH8BFqsTi+EnnqzukBbXjdSK2fUf2h43nU4ddYLV2epP767MDKwJME0maknscoqlTSCLiWbSeHy8=
